<script src="<?= base_url('assets/js/'); ?>bootstrap.min.js"></script>
<script src="<?= base_url('assets/js/'); ?>jquery-1.12.4.js"></script>
<script src="<?= base_url('assets/js/'); ?>jquery-ui.js"></script>
<script src="<?= base_url('assets/js/'); ?>jquery-3.4.1.min.js"></script>
<script src="<?= base_url('assets/js/'); ?>all.min.js"></script>
<script src="<?= base_url('assets/js/'); ?>fontawesome.min.js"></script>
<script src="<?= base_url('assets/js/'); ?>datatables.min.js"></script>
<script src="<?= base_url('assets/js/'); ?>jquery.dataTables.min.js"></script>
<script src="<?= base_url('assets/js/'); ?>dataTables.bootstrap5.min.js"></script>
<script src="<?= base_url('assets/js/'); ?>popper.min.js"></script>
<script src="<?= base_url('assets/js/'); ?>myjs.js"></script>